// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "yuv2rgb.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic yuv2rgb::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic yuv2rgb::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> yuv2rgb::ap_ST_fsm_state1 = "1";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state2 = "10";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state3 = "100";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state4 = "1000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state5 = "10000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state6 = "100000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> yuv2rgb::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> yuv2rgb::ap_const_lv32_1 = "1";
const sc_lv<1> yuv2rgb::ap_const_lv1_0 = "0";
const sc_lv<32> yuv2rgb::ap_const_lv32_2 = "10";
const sc_lv<32> yuv2rgb::ap_const_lv32_3 = "11";
const sc_lv<32> yuv2rgb::ap_const_lv32_5 = "101";
const sc_lv<32> yuv2rgb::ap_const_lv32_6 = "110";
const sc_lv<32> yuv2rgb::ap_const_lv32_7 = "111";
const sc_lv<32> yuv2rgb::ap_const_lv32_8 = "1000";
const sc_lv<16> yuv2rgb::ap_const_lv16_0 = "0000000000000000";
const sc_lv<1> yuv2rgb::ap_const_lv1_1 = "1";
const sc_lv<32> yuv2rgb::ap_const_lv32_9 = "1001";
const sc_lv<32> yuv2rgb::ap_const_lv32_4 = "100";
const sc_lv<16> yuv2rgb::ap_const_lv16_1 = "1";
const sc_lv<10> yuv2rgb::ap_const_lv10_0 = "0000000000";
const sc_lv<8> yuv2rgb::ap_const_lv8_0 = "00000000";
const sc_lv<9> yuv2rgb::ap_const_lv9_1F0 = "111110000";
const sc_lv<8> yuv2rgb::ap_const_lv8_80 = "10000000";
const sc_lv<17> yuv2rgb::ap_const_lv17_1FF30 = "11111111100110000";
const sc_lv<32> yuv2rgb::ap_const_lv32_10 = "10000";
const sc_lv<32> yuv2rgb::ap_const_lv32_11 = "10001";
const sc_lv<2> yuv2rgb::ap_const_lv2_1 = "1";
const sc_lv<32> yuv2rgb::ap_const_lv32_F = "1111";
const sc_lv<8> yuv2rgb::ap_const_lv8_FF = "11111111";
const sc_lv<9> yuv2rgb::ap_const_lv9_0 = "000000000";
const sc_lv<2> yuv2rgb::ap_const_lv2_0 = "00";
const sc_lv<32> yuv2rgb::ap_const_lv32_12 = "10010";
const sc_lv<3> yuv2rgb::ap_const_lv3_0 = "000";
const sc_lv<18> yuv2rgb::ap_const_lv18_12A = "100101010";
const sc_lv<18> yuv2rgb::ap_const_lv18_80 = "10000000";
const sc_lv<18> yuv2rgb::ap_const_lv18_199 = "110011001";
const sc_lv<16> yuv2rgb::ap_const_lv16_FF9C = "1111111110011100";
const bool yuv2rgb::ap_const_boolean_1 = true;

yuv2rgb::yuv2rgb(sc_module_name name) : sc_module(name), mVcdFile(0) {
    yuv_filter_mac_mueOg_U15 = new yuv_filter_mac_mueOg<1,1,10,9,9,18>("yuv_filter_mac_mueOg_U15");
    yuv_filter_mac_mueOg_U15->din0(grp_fu_547_p0);
    yuv_filter_mac_mueOg_U15->din1(C_fu_299_p2);
    yuv_filter_mac_mueOg_U15->din2(grp_fu_547_p2);
    yuv_filter_mac_mueOg_U15->dout(grp_fu_547_p3);
    yuv_filter_mac_mufYi_U16 = new yuv_filter_mac_mufYi<1,1,10,8,18,18>("yuv_filter_mac_mufYi_U16");
    yuv_filter_mac_mufYi_U16->din0(grp_fu_555_p0);
    yuv_filter_mac_mufYi_U16->din1(E_reg_642);
    yuv_filter_mac_mufYi_U16->din2(add_ln96_reg_647);
    yuv_filter_mac_mufYi_U16->dout(grp_fu_555_p3);
    yuv_filter_mac_mug8j_U17 = new yuv_filter_mac_mug8j<1,1,8,8,17,17>("yuv_filter_mac_mug8j_U17");
    yuv_filter_mac_mug8j_U17->din0(grp_fu_565_p0);
    yuv_filter_mac_mug8j_U17->din1(D_reg_635);
    yuv_filter_mac_mug8j_U17->din2(mul_ln97_1_reg_654);
    yuv_filter_mac_mug8j_U17->dout(grp_fu_565_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_B_fu_539_p3);
    sensitive << ( or_ln98_fu_533_p2 );
    sensitive << ( select_ln98_fu_525_p3 );
    sensitive << ( trunc_ln4_fu_515_p4 );

    SC_METHOD(thread_C_fu_299_p2);
    sensitive << ( zext_ln93_fu_296_p1 );

    SC_METHOD(thread_D_fu_305_p2);
    sensitive << ( in_channels_ch2_q0 );

    SC_METHOD(thread_E_fu_311_p2);
    sensitive << ( in_channels_ch3_q0 );

    SC_METHOD(thread_G_fu_446_p3);
    sensitive << ( or_ln97_fu_440_p2 );
    sensitive << ( select_ln97_fu_432_p3 );
    sensitive << ( trunc_ln3_fu_422_p4 );

    SC_METHOD(thread_R_fu_379_p3);
    sensitive << ( or_ln96_fu_373_p2 );
    sensitive << ( select_ln96_fu_365_p3 );
    sensitive << ( trunc_ln_fu_356_p4 );

    SC_METHOD(thread_add_ln90_1_fu_286_p2);
    sensitive << ( add_ln90_reg_593 );
    sensitive << ( zext_ln90_fu_282_p1 );

    SC_METHOD(thread_add_ln90_fu_255_p2);
    sensitive << ( zext_ln90_cast_fu_235_p3 );
    sensitive << ( zext_ln90_2_cast_fu_247_p3 );

    SC_METHOD(thread_add_ln97_1_fu_393_p2);
    sensitive << ( add_ln96_reg_647 );
    sensitive << ( sext_ln97_2_fu_390_p1 );

    SC_METHOD(thread_add_ln98_1_fu_476_p2);
    sensitive << ( add_ln96_reg_647 );
    sensitive << ( sext_ln98_1_fu_472_p1 );

    SC_METHOD(thread_add_ln98_fu_485_p2);
    sensitive << ( sext_ln98_2_fu_481_p1 );
    sensitive << ( sext_ln98_fu_461_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln85_fu_220_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln85_fu_220_p2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( in_width_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln85_fu_220_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( in_height_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln85_fu_220_p2 );

    SC_METHOD(thread_grp_fu_547_p0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_547_p2);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_555_p0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_565_p0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_icmp_ln85_fu_220_p2);
    sensitive << ( in_width_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_0_reg_198 );

    SC_METHOD(thread_icmp_ln88_fu_271_p2);
    sensitive << ( in_height_read );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_0_reg_209 );

    SC_METHOD(thread_icmp_ln96_fu_343_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_1_fu_334_p4 );

    SC_METHOD(thread_icmp_ln97_fu_408_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_4_fu_398_p4 );

    SC_METHOD(thread_icmp_ln98_fu_501_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_6_fu_491_p4 );

    SC_METHOD(thread_in_channels_ch1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln90_1_fu_291_p1 );

    SC_METHOD(thread_in_channels_ch1_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_in_channels_ch2_address0);
    sensitive << ( zext_ln90_1_reg_606 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_channels_ch2_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_in_channels_ch3_address0);
    sensitive << ( zext_ln90_1_reg_606 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_channels_ch3_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mul_ln97_1_fu_325_p1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( E_fu_311_p2 );

    SC_METHOD(thread_mul_ln97_1_fu_325_p2);
    sensitive << ( mul_ln97_1_fu_325_p1 );

    SC_METHOD(thread_or_ln96_fu_373_p2);
    sensitive << ( icmp_ln96_fu_343_p2 );
    sensitive << ( tmp_3_fu_349_p3 );

    SC_METHOD(thread_or_ln97_fu_440_p2);
    sensitive << ( icmp_ln97_fu_408_p2 );
    sensitive << ( tmp_5_fu_414_p3 );

    SC_METHOD(thread_or_ln98_fu_533_p2);
    sensitive << ( icmp_ln98_fu_501_p2 );
    sensitive << ( tmp_7_fu_507_p3 );

    SC_METHOD(thread_out_channels_ch1_address0);
    sensitive << ( zext_ln90_1_reg_606 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch1_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch1_d0);
    sensitive << ( R_reg_659 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch1_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_address0);
    sensitive << ( zext_ln90_1_reg_606 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch2_d0);
    sensitive << ( G_reg_664 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_address0);
    sensitive << ( zext_ln90_1_reg_606 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch3_d0);
    sensitive << ( B_reg_669 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_select_ln96_fu_365_p3);
    sensitive << ( icmp_ln96_fu_343_p2 );

    SC_METHOD(thread_select_ln97_fu_432_p3);
    sensitive << ( icmp_ln97_fu_408_p2 );

    SC_METHOD(thread_select_ln98_fu_525_p3);
    sensitive << ( icmp_ln98_fu_501_p2 );

    SC_METHOD(thread_sext_ln97_2_fu_390_p1);
    sensitive << ( grp_fu_565_p3 );

    SC_METHOD(thread_sext_ln98_1_fu_472_p1);
    sensitive << ( shl_ln98_1_fu_465_p3 );

    SC_METHOD(thread_sext_ln98_2_fu_481_p1);
    sensitive << ( add_ln98_1_fu_476_p2 );

    SC_METHOD(thread_sext_ln98_fu_461_p1);
    sensitive << ( shl_ln_fu_454_p3 );

    SC_METHOD(thread_shl_ln98_1_fu_465_p3);
    sensitive << ( D_reg_635 );

    SC_METHOD(thread_shl_ln_fu_454_p3);
    sensitive << ( D_reg_635 );

    SC_METHOD(thread_tmp_1_fu_334_p4);
    sensitive << ( grp_fu_555_p3 );

    SC_METHOD(thread_tmp_3_fu_349_p3);
    sensitive << ( grp_fu_555_p3 );

    SC_METHOD(thread_tmp_4_fu_398_p4);
    sensitive << ( add_ln97_1_fu_393_p2 );

    SC_METHOD(thread_tmp_5_fu_414_p3);
    sensitive << ( add_ln97_1_fu_393_p2 );

    SC_METHOD(thread_tmp_6_fu_491_p4);
    sensitive << ( add_ln98_fu_485_p2 );

    SC_METHOD(thread_tmp_7_fu_507_p3);
    sensitive << ( add_ln98_fu_485_p2 );

    SC_METHOD(thread_trunc_ln3_fu_422_p4);
    sensitive << ( add_ln97_1_fu_393_p2 );

    SC_METHOD(thread_trunc_ln4_fu_515_p4);
    sensitive << ( add_ln98_fu_485_p2 );

    SC_METHOD(thread_trunc_ln90_1_fu_243_p1);
    sensitive << ( x_0_reg_198 );

    SC_METHOD(thread_trunc_ln90_fu_231_p1);
    sensitive << ( x_0_reg_198 );

    SC_METHOD(thread_trunc_ln_fu_356_p4);
    sensitive << ( grp_fu_555_p3 );

    SC_METHOD(thread_x_fu_225_p2);
    sensitive << ( x_0_reg_198 );

    SC_METHOD(thread_y_fu_276_p2);
    sensitive << ( y_0_reg_209 );

    SC_METHOD(thread_zext_ln90_1_fu_291_p1);
    sensitive << ( add_ln90_1_fu_286_p2 );

    SC_METHOD(thread_zext_ln90_2_cast_fu_247_p3);
    sensitive << ( trunc_ln90_1_fu_243_p1 );

    SC_METHOD(thread_zext_ln90_cast_fu_235_p3);
    sensitive << ( trunc_ln90_fu_231_p1 );

    SC_METHOD(thread_zext_ln90_fu_282_p1);
    sensitive << ( y_0_reg_209 );

    SC_METHOD(thread_zext_ln93_fu_296_p1);
    sensitive << ( Y_reg_630 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln85_fu_220_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln88_fu_271_p2 );

    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "yuv2rgb_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_channels_ch1_address0, "(port)in_channels_ch1_address0");
    sc_trace(mVcdFile, in_channels_ch1_ce0, "(port)in_channels_ch1_ce0");
    sc_trace(mVcdFile, in_channels_ch1_q0, "(port)in_channels_ch1_q0");
    sc_trace(mVcdFile, in_channels_ch2_address0, "(port)in_channels_ch2_address0");
    sc_trace(mVcdFile, in_channels_ch2_ce0, "(port)in_channels_ch2_ce0");
    sc_trace(mVcdFile, in_channels_ch2_q0, "(port)in_channels_ch2_q0");
    sc_trace(mVcdFile, in_channels_ch3_address0, "(port)in_channels_ch3_address0");
    sc_trace(mVcdFile, in_channels_ch3_ce0, "(port)in_channels_ch3_ce0");
    sc_trace(mVcdFile, in_channels_ch3_q0, "(port)in_channels_ch3_q0");
    sc_trace(mVcdFile, in_width_read, "(port)in_width_read");
    sc_trace(mVcdFile, in_height_read, "(port)in_height_read");
    sc_trace(mVcdFile, out_channels_ch1_address0, "(port)out_channels_ch1_address0");
    sc_trace(mVcdFile, out_channels_ch1_ce0, "(port)out_channels_ch1_ce0");
    sc_trace(mVcdFile, out_channels_ch1_we0, "(port)out_channels_ch1_we0");
    sc_trace(mVcdFile, out_channels_ch1_d0, "(port)out_channels_ch1_d0");
    sc_trace(mVcdFile, out_channels_ch2_address0, "(port)out_channels_ch2_address0");
    sc_trace(mVcdFile, out_channels_ch2_ce0, "(port)out_channels_ch2_ce0");
    sc_trace(mVcdFile, out_channels_ch2_we0, "(port)out_channels_ch2_we0");
    sc_trace(mVcdFile, out_channels_ch2_d0, "(port)out_channels_ch2_d0");
    sc_trace(mVcdFile, out_channels_ch3_address0, "(port)out_channels_ch3_address0");
    sc_trace(mVcdFile, out_channels_ch3_ce0, "(port)out_channels_ch3_ce0");
    sc_trace(mVcdFile, out_channels_ch3_we0, "(port)out_channels_ch3_we0");
    sc_trace(mVcdFile, out_channels_ch3_d0, "(port)out_channels_ch3_d0");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, x_fu_225_p2, "x_fu_225_p2");
    sc_trace(mVcdFile, x_reg_588, "x_reg_588");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln90_fu_255_p2, "add_ln90_fu_255_p2");
    sc_trace(mVcdFile, add_ln90_reg_593, "add_ln90_reg_593");
    sc_trace(mVcdFile, icmp_ln85_fu_220_p2, "icmp_ln85_fu_220_p2");
    sc_trace(mVcdFile, y_fu_276_p2, "y_fu_276_p2");
    sc_trace(mVcdFile, y_reg_601, "y_reg_601");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln90_1_fu_291_p1, "zext_ln90_1_fu_291_p1");
    sc_trace(mVcdFile, zext_ln90_1_reg_606, "zext_ln90_1_reg_606");
    sc_trace(mVcdFile, icmp_ln88_fu_271_p2, "icmp_ln88_fu_271_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, Y_reg_630, "Y_reg_630");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, D_fu_305_p2, "D_fu_305_p2");
    sc_trace(mVcdFile, D_reg_635, "D_reg_635");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, E_fu_311_p2, "E_fu_311_p2");
    sc_trace(mVcdFile, E_reg_642, "E_reg_642");
    sc_trace(mVcdFile, grp_fu_547_p3, "grp_fu_547_p3");
    sc_trace(mVcdFile, add_ln96_reg_647, "add_ln96_reg_647");
    sc_trace(mVcdFile, mul_ln97_1_fu_325_p2, "mul_ln97_1_fu_325_p2");
    sc_trace(mVcdFile, mul_ln97_1_reg_654, "mul_ln97_1_reg_654");
    sc_trace(mVcdFile, R_fu_379_p3, "R_fu_379_p3");
    sc_trace(mVcdFile, R_reg_659, "R_reg_659");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, G_fu_446_p3, "G_fu_446_p3");
    sc_trace(mVcdFile, G_reg_664, "G_reg_664");
    sc_trace(mVcdFile, B_fu_539_p3, "B_fu_539_p3");
    sc_trace(mVcdFile, B_reg_669, "B_reg_669");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, x_0_reg_198, "x_0_reg_198");
    sc_trace(mVcdFile, y_0_reg_209, "y_0_reg_209");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, trunc_ln90_fu_231_p1, "trunc_ln90_fu_231_p1");
    sc_trace(mVcdFile, trunc_ln90_1_fu_243_p1, "trunc_ln90_1_fu_243_p1");
    sc_trace(mVcdFile, zext_ln90_cast_fu_235_p3, "zext_ln90_cast_fu_235_p3");
    sc_trace(mVcdFile, zext_ln90_2_cast_fu_247_p3, "zext_ln90_2_cast_fu_247_p3");
    sc_trace(mVcdFile, zext_ln90_fu_282_p1, "zext_ln90_fu_282_p1");
    sc_trace(mVcdFile, add_ln90_1_fu_286_p2, "add_ln90_1_fu_286_p2");
    sc_trace(mVcdFile, zext_ln93_fu_296_p1, "zext_ln93_fu_296_p1");
    sc_trace(mVcdFile, C_fu_299_p2, "C_fu_299_p2");
    sc_trace(mVcdFile, mul_ln97_1_fu_325_p1, "mul_ln97_1_fu_325_p1");
    sc_trace(mVcdFile, grp_fu_555_p3, "grp_fu_555_p3");
    sc_trace(mVcdFile, tmp_1_fu_334_p4, "tmp_1_fu_334_p4");
    sc_trace(mVcdFile, icmp_ln96_fu_343_p2, "icmp_ln96_fu_343_p2");
    sc_trace(mVcdFile, tmp_3_fu_349_p3, "tmp_3_fu_349_p3");
    sc_trace(mVcdFile, or_ln96_fu_373_p2, "or_ln96_fu_373_p2");
    sc_trace(mVcdFile, select_ln96_fu_365_p3, "select_ln96_fu_365_p3");
    sc_trace(mVcdFile, trunc_ln_fu_356_p4, "trunc_ln_fu_356_p4");
    sc_trace(mVcdFile, grp_fu_565_p3, "grp_fu_565_p3");
    sc_trace(mVcdFile, sext_ln97_2_fu_390_p1, "sext_ln97_2_fu_390_p1");
    sc_trace(mVcdFile, add_ln97_1_fu_393_p2, "add_ln97_1_fu_393_p2");
    sc_trace(mVcdFile, tmp_4_fu_398_p4, "tmp_4_fu_398_p4");
    sc_trace(mVcdFile, icmp_ln97_fu_408_p2, "icmp_ln97_fu_408_p2");
    sc_trace(mVcdFile, tmp_5_fu_414_p3, "tmp_5_fu_414_p3");
    sc_trace(mVcdFile, or_ln97_fu_440_p2, "or_ln97_fu_440_p2");
    sc_trace(mVcdFile, select_ln97_fu_432_p3, "select_ln97_fu_432_p3");
    sc_trace(mVcdFile, trunc_ln3_fu_422_p4, "trunc_ln3_fu_422_p4");
    sc_trace(mVcdFile, shl_ln_fu_454_p3, "shl_ln_fu_454_p3");
    sc_trace(mVcdFile, shl_ln98_1_fu_465_p3, "shl_ln98_1_fu_465_p3");
    sc_trace(mVcdFile, sext_ln98_1_fu_472_p1, "sext_ln98_1_fu_472_p1");
    sc_trace(mVcdFile, add_ln98_1_fu_476_p2, "add_ln98_1_fu_476_p2");
    sc_trace(mVcdFile, sext_ln98_2_fu_481_p1, "sext_ln98_2_fu_481_p1");
    sc_trace(mVcdFile, sext_ln98_fu_461_p1, "sext_ln98_fu_461_p1");
    sc_trace(mVcdFile, add_ln98_fu_485_p2, "add_ln98_fu_485_p2");
    sc_trace(mVcdFile, tmp_6_fu_491_p4, "tmp_6_fu_491_p4");
    sc_trace(mVcdFile, icmp_ln98_fu_501_p2, "icmp_ln98_fu_501_p2");
    sc_trace(mVcdFile, tmp_7_fu_507_p3, "tmp_7_fu_507_p3");
    sc_trace(mVcdFile, or_ln98_fu_533_p2, "or_ln98_fu_533_p2");
    sc_trace(mVcdFile, select_ln98_fu_525_p3, "select_ln98_fu_525_p3");
    sc_trace(mVcdFile, trunc_ln4_fu_515_p4, "trunc_ln4_fu_515_p4");
    sc_trace(mVcdFile, grp_fu_547_p0, "grp_fu_547_p0");
    sc_trace(mVcdFile, grp_fu_547_p2, "grp_fu_547_p2");
    sc_trace(mVcdFile, grp_fu_555_p0, "grp_fu_555_p0");
    sc_trace(mVcdFile, grp_fu_565_p0, "grp_fu_565_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

yuv2rgb::~yuv2rgb() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete yuv_filter_mac_mueOg_U15;
    delete yuv_filter_mac_mufYi_U16;
    delete yuv_filter_mac_mug8j_U17;
}

void yuv2rgb::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln88_fu_271_p2.read(), ap_const_lv1_1))) {
        x_0_reg_198 = x_reg_588.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_0_reg_198 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        y_0_reg_209 = y_reg_601.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln85_fu_220_p2.read(), ap_const_lv1_0))) {
        y_0_reg_209 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        B_reg_669 = B_fu_539_p3.read();
        G_reg_664 = G_fu_446_p3.read();
        R_reg_659 = R_fu_379_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        D_reg_635 = D_fu_305_p2.read();
        E_reg_642 = E_fu_311_p2.read();
        add_ln96_reg_647 = grp_fu_547_p3.read();
        mul_ln97_1_reg_654 = mul_ln97_1_fu_325_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        Y_reg_630 = in_channels_ch1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln85_fu_220_p2.read(), ap_const_lv1_0))) {
        add_ln90_reg_593 = add_ln90_fu_255_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_reg_588 = x_fu_225_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        y_reg_601 = y_fu_276_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_271_p2.read()))) {
        zext_ln90_1_reg_606 = zext_ln90_1_fu_291_p1.read();
    }
}

void yuv2rgb::thread_B_fu_539_p3() {
    B_fu_539_p3 = (!or_ln98_fu_533_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln98_fu_533_p2.read()[0].to_bool())? select_ln98_fu_525_p3.read(): trunc_ln4_fu_515_p4.read());
}

void yuv2rgb::thread_C_fu_299_p2() {
    C_fu_299_p2 = (!ap_const_lv9_1F0.is_01() || !zext_ln93_fu_296_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1F0) + sc_biguint<9>(zext_ln93_fu_296_p1.read()));
}

void yuv2rgb::thread_D_fu_305_p2() {
    D_fu_305_p2 = (in_channels_ch2_q0.read() ^ ap_const_lv8_80);
}

void yuv2rgb::thread_E_fu_311_p2() {
    E_fu_311_p2 = (in_channels_ch3_q0.read() ^ ap_const_lv8_80);
}

void yuv2rgb::thread_G_fu_446_p3() {
    G_fu_446_p3 = (!or_ln97_fu_440_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln97_fu_440_p2.read()[0].to_bool())? select_ln97_fu_432_p3.read(): trunc_ln3_fu_422_p4.read());
}

void yuv2rgb::thread_R_fu_379_p3() {
    R_fu_379_p3 = (!or_ln96_fu_373_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln96_fu_373_p2.read()[0].to_bool())? select_ln96_fu_365_p3.read(): trunc_ln_fu_356_p4.read());
}

void yuv2rgb::thread_add_ln90_1_fu_286_p2() {
    add_ln90_1_fu_286_p2 = (!zext_ln90_fu_282_p1.read().is_01() || !add_ln90_reg_593.read().is_01())? sc_lv<23>(): (sc_biguint<23>(zext_ln90_fu_282_p1.read()) + sc_biguint<23>(add_ln90_reg_593.read()));
}

void yuv2rgb::thread_add_ln90_fu_255_p2() {
    add_ln90_fu_255_p2 = (!zext_ln90_cast_fu_235_p3.read().is_01() || !zext_ln90_2_cast_fu_247_p3.read().is_01())? sc_lv<23>(): (sc_biguint<23>(zext_ln90_cast_fu_235_p3.read()) + sc_biguint<23>(zext_ln90_2_cast_fu_247_p3.read()));
}

void yuv2rgb::thread_add_ln97_1_fu_393_p2() {
    add_ln97_1_fu_393_p2 = (!sext_ln97_2_fu_390_p1.read().is_01() || !add_ln96_reg_647.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln97_2_fu_390_p1.read()) + sc_bigint<18>(add_ln96_reg_647.read()));
}

void yuv2rgb::thread_add_ln98_1_fu_476_p2() {
    add_ln98_1_fu_476_p2 = (!sext_ln98_1_fu_472_p1.read().is_01() || !add_ln96_reg_647.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln98_1_fu_472_p1.read()) + sc_bigint<18>(add_ln96_reg_647.read()));
}

void yuv2rgb::thread_add_ln98_fu_485_p2() {
    add_ln98_fu_485_p2 = (!sext_ln98_2_fu_481_p1.read().is_01() || !sext_ln98_fu_461_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(sext_ln98_2_fu_481_p1.read()) + sc_bigint<19>(sext_ln98_fu_461_p1.read()));
}

void yuv2rgb::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void yuv2rgb::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void yuv2rgb::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void yuv2rgb::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void yuv2rgb::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void yuv2rgb::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void yuv2rgb::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void yuv2rgb::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void yuv2rgb::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void yuv2rgb::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void yuv2rgb::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln85_fu_220_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void yuv2rgb::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void yuv2rgb::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln85_fu_220_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void yuv2rgb::thread_ap_return_0() {
    ap_return_0 = in_width_read.read();
}

void yuv2rgb::thread_ap_return_1() {
    ap_return_1 = in_height_read.read();
}

void yuv2rgb::thread_grp_fu_547_p0() {
    grp_fu_547_p0 =  (sc_lv<10>) (ap_const_lv18_12A);
}

void yuv2rgb::thread_grp_fu_547_p2() {
    grp_fu_547_p2 =  (sc_lv<9>) (ap_const_lv18_80);
}

void yuv2rgb::thread_grp_fu_555_p0() {
    grp_fu_555_p0 =  (sc_lv<10>) (ap_const_lv18_199);
}

void yuv2rgb::thread_grp_fu_565_p0() {
    grp_fu_565_p0 =  (sc_lv<8>) (ap_const_lv16_FF9C);
}

void yuv2rgb::thread_icmp_ln85_fu_220_p2() {
    icmp_ln85_fu_220_p2 = (!x_0_reg_198.read().is_01() || !in_width_read.read().is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_198.read() == in_width_read.read());
}

void yuv2rgb::thread_icmp_ln88_fu_271_p2() {
    icmp_ln88_fu_271_p2 = (!y_0_reg_209.read().is_01() || !in_height_read.read().is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_209.read() == in_height_read.read());
}

void yuv2rgb::thread_icmp_ln96_fu_343_p2() {
    icmp_ln96_fu_343_p2 = (!tmp_1_fu_334_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_334_p4.read() == ap_const_lv2_1);
}

void yuv2rgb::thread_icmp_ln97_fu_408_p2() {
    icmp_ln97_fu_408_p2 = (!tmp_4_fu_398_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_398_p4.read() == ap_const_lv2_1);
}

void yuv2rgb::thread_icmp_ln98_fu_501_p2() {
    icmp_ln98_fu_501_p2 = (!tmp_6_fu_491_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): (sc_bigint<3>(tmp_6_fu_491_p4.read()) > sc_bigint<3>(ap_const_lv3_0));
}

void yuv2rgb::thread_in_channels_ch1_address0() {
    in_channels_ch1_address0 =  (sc_lv<22>) (zext_ln90_1_fu_291_p1.read());
}

void yuv2rgb::thread_in_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_in_channels_ch2_address0() {
    in_channels_ch2_address0 =  (sc_lv<22>) (zext_ln90_1_reg_606.read());
}

void yuv2rgb::thread_in_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_in_channels_ch3_address0() {
    in_channels_ch3_address0 =  (sc_lv<22>) (zext_ln90_1_reg_606.read());
}

void yuv2rgb::thread_in_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_mul_ln97_1_fu_325_p1() {
    mul_ln97_1_fu_325_p1 = E_fu_311_p2.read();
}

void yuv2rgb::thread_mul_ln97_1_fu_325_p2() {
    mul_ln97_1_fu_325_p2 = (!ap_const_lv17_1FF30.is_01() || !mul_ln97_1_fu_325_p1.read().is_01())? sc_lv<17>(): sc_bigint<17>(ap_const_lv17_1FF30) * sc_bigint<8>(mul_ln97_1_fu_325_p1.read());
}

void yuv2rgb::thread_or_ln96_fu_373_p2() {
    or_ln96_fu_373_p2 = (icmp_ln96_fu_343_p2.read() | tmp_3_fu_349_p3.read());
}

void yuv2rgb::thread_or_ln97_fu_440_p2() {
    or_ln97_fu_440_p2 = (icmp_ln97_fu_408_p2.read() | tmp_5_fu_414_p3.read());
}

void yuv2rgb::thread_or_ln98_fu_533_p2() {
    or_ln98_fu_533_p2 = (icmp_ln98_fu_501_p2.read() | tmp_7_fu_507_p3.read());
}

void yuv2rgb::thread_out_channels_ch1_address0() {
    out_channels_ch1_address0 =  (sc_lv<22>) (zext_ln90_1_reg_606.read());
}

void yuv2rgb::thread_out_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch1_d0() {
    out_channels_ch1_d0 = R_reg_659.read();
}

void yuv2rgb::thread_out_channels_ch1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch1_we0 = ap_const_logic_1;
    } else {
        out_channels_ch1_we0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch2_address0() {
    out_channels_ch2_address0 =  (sc_lv<22>) (zext_ln90_1_reg_606.read());
}

void yuv2rgb::thread_out_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch2_d0() {
    out_channels_ch2_d0 = G_reg_664.read();
}

void yuv2rgb::thread_out_channels_ch2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch2_we0 = ap_const_logic_1;
    } else {
        out_channels_ch2_we0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch3_address0() {
    out_channels_ch3_address0 =  (sc_lv<22>) (zext_ln90_1_reg_606.read());
}

void yuv2rgb::thread_out_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch3_d0() {
    out_channels_ch3_d0 = B_reg_669.read();
}

void yuv2rgb::thread_out_channels_ch3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch3_we0 = ap_const_logic_1;
    } else {
        out_channels_ch3_we0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_select_ln96_fu_365_p3() {
    select_ln96_fu_365_p3 = (!icmp_ln96_fu_343_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln96_fu_343_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv2rgb::thread_select_ln97_fu_432_p3() {
    select_ln97_fu_432_p3 = (!icmp_ln97_fu_408_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln97_fu_408_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv2rgb::thread_select_ln98_fu_525_p3() {
    select_ln98_fu_525_p3 = (!icmp_ln98_fu_501_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln98_fu_501_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv2rgb::thread_sext_ln97_2_fu_390_p1() {
    sext_ln97_2_fu_390_p1 = esl_sext<18,17>(grp_fu_565_p3.read());
}

void yuv2rgb::thread_sext_ln98_1_fu_472_p1() {
    sext_ln98_1_fu_472_p1 = esl_sext<18,10>(shl_ln98_1_fu_465_p3.read());
}

void yuv2rgb::thread_sext_ln98_2_fu_481_p1() {
    sext_ln98_2_fu_481_p1 = esl_sext<19,18>(add_ln98_1_fu_476_p2.read());
}

void yuv2rgb::thread_sext_ln98_fu_461_p1() {
    sext_ln98_fu_461_p1 = esl_sext<19,17>(shl_ln_fu_454_p3.read());
}

void yuv2rgb::thread_shl_ln98_1_fu_465_p3() {
    shl_ln98_1_fu_465_p3 = esl_concat<8,2>(D_reg_635.read(), ap_const_lv2_0);
}

void yuv2rgb::thread_shl_ln_fu_454_p3() {
    shl_ln_fu_454_p3 = esl_concat<8,9>(D_reg_635.read(), ap_const_lv9_0);
}

void yuv2rgb::thread_tmp_1_fu_334_p4() {
    tmp_1_fu_334_p4 = grp_fu_555_p3.read().range(17, 16);
}

void yuv2rgb::thread_tmp_3_fu_349_p3() {
    tmp_3_fu_349_p3 = grp_fu_555_p3.read().range(17, 17);
}

void yuv2rgb::thread_tmp_4_fu_398_p4() {
    tmp_4_fu_398_p4 = add_ln97_1_fu_393_p2.read().range(17, 16);
}

void yuv2rgb::thread_tmp_5_fu_414_p3() {
    tmp_5_fu_414_p3 = add_ln97_1_fu_393_p2.read().range(17, 17);
}

void yuv2rgb::thread_tmp_6_fu_491_p4() {
    tmp_6_fu_491_p4 = add_ln98_fu_485_p2.read().range(18, 16);
}

void yuv2rgb::thread_tmp_7_fu_507_p3() {
    tmp_7_fu_507_p3 = add_ln98_fu_485_p2.read().range(18, 18);
}

void yuv2rgb::thread_trunc_ln3_fu_422_p4() {
    trunc_ln3_fu_422_p4 = add_ln97_1_fu_393_p2.read().range(15, 8);
}

void yuv2rgb::thread_trunc_ln4_fu_515_p4() {
    trunc_ln4_fu_515_p4 = add_ln98_fu_485_p2.read().range(15, 8);
}

void yuv2rgb::thread_trunc_ln90_1_fu_243_p1() {
    trunc_ln90_1_fu_243_p1 = x_0_reg_198.read().range(15-1, 0);
}

void yuv2rgb::thread_trunc_ln90_fu_231_p1() {
    trunc_ln90_fu_231_p1 = x_0_reg_198.read().range(13-1, 0);
}

void yuv2rgb::thread_trunc_ln_fu_356_p4() {
    trunc_ln_fu_356_p4 = grp_fu_555_p3.read().range(15, 8);
}

void yuv2rgb::thread_x_fu_225_p2() {
    x_fu_225_p2 = (!x_0_reg_198.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(x_0_reg_198.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void yuv2rgb::thread_y_fu_276_p2() {
    y_fu_276_p2 = (!y_0_reg_209.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(y_0_reg_209.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void yuv2rgb::thread_zext_ln90_1_fu_291_p1() {
    zext_ln90_1_fu_291_p1 = esl_zext<64,23>(add_ln90_1_fu_286_p2.read());
}

void yuv2rgb::thread_zext_ln90_2_cast_fu_247_p3() {
    zext_ln90_2_cast_fu_247_p3 = esl_concat<15,8>(trunc_ln90_1_fu_243_p1.read(), ap_const_lv8_0);
}

void yuv2rgb::thread_zext_ln90_cast_fu_235_p3() {
    zext_ln90_cast_fu_235_p3 = esl_concat<13,10>(trunc_ln90_fu_231_p1.read(), ap_const_lv10_0);
}

void yuv2rgb::thread_zext_ln90_fu_282_p1() {
    zext_ln90_fu_282_p1 = esl_zext<23,16>(y_0_reg_209.read());
}

void yuv2rgb::thread_zext_ln93_fu_296_p1() {
    zext_ln93_fu_296_p1 = esl_zext<9,8>(Y_reg_630.read());
}

void yuv2rgb::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln85_fu_220_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln88_fu_271_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

